platform:
  - Win32

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  BOOST_LIBRARYDIR64: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
  BUILD_EXAMPLES: OFF  # don't build examples to not exceed allowed build time (40 min) 
  
  matrix:
     - GENERATOR: "Visual Studio 14"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14"
       CONFIG: Release       
       
matrix:
  fast_finish: true
    
  
#----------------------------------------------------------------------------------------  
# lets go	
init:
  - cmake --version
  - msbuild /version
  - dir C:\Libraries
  
install:
  - ps: Start-FileDownload https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - 7z x gtest-1.7.0.zip > NUL
  - cd gtest-1.7.0
  - md build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON ..
  - cmake --build . --config Release
  - cmake --build . --config Debug
  - cd ../..
  - if %platform%==Win32 set generator=Visual Studio 14
  - if %platform%==Win64 set generator=Visual Studio 14 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64
  - set GTEST_LIBRARY=%APPVEYOR_BUILD_FOLDER%\gtest-1.7.0\build\Release\gtest.lib
  - set GTESTD_LIBRARY=%APPVEYOR_BUILD_FOLDER%\gtest-1.7.0\build\Debug\gtest.lib

build_script:
  - cmd: cd cpp_uriparser
  - cmake . -B"build" -G"Visual Studio 14" -Wno-dev -DBOOST_ROOT="%BOOST_ROOT%" -DGTEST_FOLDER="%APPVEYOR_BUILD_FOLDER%\gtest-1.7.0"
  - cmake --build "build" --config %CONFIG%
